export const MIN_BLOG_TITLE_LENGTH = 3;
export const MAX_BLOG_TITLE_LENGTH = 100;

export const MIN_BLOG_SUMMARY_LENGTH = 30;
export const MAX_BLOG_SUMMARY_LENGTH = 400;

export const MIN_BLOG_CONTENT_LENGTH = 50;
export const MAX_BLOG_CONTENT_LENGTH = 5000;

export const MIN_BLOG_DESCRIPTION_LENGTH = 50;
export const MAX_BLOG_DESCRIPTION_LENGTH = 160;

export const MIN_COURSE_YEAR = 2010;
export const MAX_COURSE_YEAR = 2030;

export const MIN_COURSE_CODE_LENGTH = 2;
export const MAX_COURSE_CODE_LENGTH = 10;

export const MIN_COURSE_CREDITS = 0;
export const MAX_COURSE_CREDITS = 20;

export const MIN_COURSE_MODE_LENGTH = 4;
export const MAX_COURSE_MODE_LENGTH = 30;

export const MIN_COURSE_TITLE_LENGTH = 3;
export const MAX_COURSE_TITLE_LENGTH = 140;

export const MIN_COURSE_SUBTITLE_LENGTH = 3;
export const MAX_COURSE_SUBTITLE_LENGTH = 140;

export const MIN_COURSE_DESCRIPTION_LENGTH = 3;
export const MAX_COURSE_DESCRIPTION_LENGTH = 5000;

export const MIN_COURSE_LOCATION_LENGTH = 3;
export const MAX_COURSE_LOCATION_LENGTH = 180;
